name = "Modrinth modpack temporary name"
author = "Sofmethod"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78ff9a0fa95257658d44da0d0c4c7fc2431b18c7370841b440d43de4ab5f695a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
