name = "Modrinth modpack temporary name"
author = "Sofmethod"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7975f4ee39e8fb247b28f4d12d032cd5d5d0b595c5a083f57b289b7e7c7a92b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
