name = "Modrinth modpack temporary name"
author = "Sofmethod"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "056338e667fd10e5056e53311f86f608c73d099afcee9b03f97f5c1f3d156bc9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"
