#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue May 26 18:08:21 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
